package com.mycompany.adp_exercise_group5;

public class MainForm extends javax.swing.JFrame {

    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTitle = new javax.swing.JLabel();
        groupTitle = new javax.swing.JLabel();
        memberTitle = new javax.swing.JLabel();
        member1 = new javax.swing.JLabel();
        member2 = new javax.swing.JLabel();
        member4 = new javax.swing.JLabel();
        member5 = new javax.swing.JLabel();
        member3 = new javax.swing.JLabel();
        funtionTitle = new javax.swing.JLabel();
        BT1 = new javax.swing.JButton();
        BT2 = new javax.swing.JButton();
        BT3 = new javax.swing.JButton();
        BT4 = new javax.swing.JButton();
        BT5 = new javax.swing.JButton();
        BT6 = new javax.swing.JButton();
        BT7 = new javax.swing.JButton();
        BT8 = new javax.swing.JButton();
        BT9 = new javax.swing.JButton();
        BT10 = new javax.swing.JButton();
        BT11 = new javax.swing.JButton();
        BT12 = new javax.swing.JButton();
        BT13 = new javax.swing.JButton();
        BT14 = new javax.swing.JButton();
        BT15 = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Group 5 - Main Form");
        setBackground(new java.awt.Color(255, 255, 255));

        mainTitle.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        mainTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainTitle.setText("GROUP EXERCISES");

        groupTitle.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        groupTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        groupTitle.setText("GROUP 5");

        memberTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        memberTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        memberTitle.setText("MEMBERS");

        member1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        member1.setText("Nguyễn Phan Trung Hiếu");

        member2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        member2.setText("Trần Ngọc Linh");

        member4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        member4.setText("Võ Ngọc Trà");

        member5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        member5.setText("Hoàng Phước Duy");

        member3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        member3.setText("Nguyễn Nhật Minh");

        funtionTitle.setFont(new java.awt.Font("Segoe UI Semibold", 2, 24)); // NOI18N
        funtionTitle.setForeground(new java.awt.Color(0, 0, 153));
        funtionTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        funtionTitle.setText("FUNCTIONS: ");

        BT1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        BT1.setForeground(new java.awt.Color(0, 102, 255));
        BT1.setText("Bai 1");
        BT1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT1ActionPerformed(evt);
            }
        });

        BT2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        BT2.setForeground(new java.awt.Color(0, 102, 255));
        BT2.setText("Bai 2");
        BT2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT2ActionPerformed(evt);
            }
        });

        BT3.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        BT3.setForeground(new java.awt.Color(0, 102, 255));
        BT3.setText("Bai 3");
        BT3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT3ActionPerformed(evt);
            }
        });

        BT4.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        BT4.setForeground(new java.awt.Color(0, 102, 255));
        BT4.setText("Bai 4");
        BT4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BT4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT4ActionPerformed(evt);
            }
        });

        BT5.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        BT5.setForeground(new java.awt.Color(0, 102, 255));
        BT5.setText("Bai 5");
        BT5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BT5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT5ActionPerformed(evt);
            }
        });

        BT6.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        BT6.setForeground(new java.awt.Color(0, 102, 255));
        BT6.setText("Bai 6");
        BT6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BT6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT6ActionPerformed(evt);
            }
        });

        BT7.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        BT7.setForeground(new java.awt.Color(0, 102, 255));
        BT7.setText("Bai 7");
        BT7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BT7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT7ActionPerformed(evt);
            }
        });

        BT8.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        BT8.setForeground(new java.awt.Color(0, 102, 255));
        BT8.setText("Bai 8");
        BT8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BT8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT8ActionPerformed(evt);
            }
        });

        BT9.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        BT9.setForeground(new java.awt.Color(0, 102, 255));
        BT9.setText("Bai 9");
        BT9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BT9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT9ActionPerformed(evt);
            }
        });

        BT10.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        BT10.setForeground(new java.awt.Color(0, 102, 255));
        BT10.setText("Bai 10");
        BT10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BT10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT10ActionPerformed(evt);
            }
        });

        BT11.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        BT11.setForeground(new java.awt.Color(0, 102, 255));
        BT11.setText("Bai 11");
        BT11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BT11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT11ActionPerformed(evt);
            }
        });

        BT12.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        BT12.setForeground(new java.awt.Color(0, 102, 255));
        BT12.setText("Bai 12");
        BT12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BT12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT12ActionPerformed(evt);
            }
        });

        BT13.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        BT13.setForeground(new java.awt.Color(0, 102, 255));
        BT13.setText("Bai 13");
        BT13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BT13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT13ActionPerformed(evt);
            }
        });

        BT14.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        BT14.setForeground(new java.awt.Color(0, 102, 255));
        BT14.setText("Bai 14");
        BT14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BT14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT14ActionPerformed(evt);
            }
        });

        BT15.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        BT15.setForeground(new java.awt.Color(0, 102, 255));
        BT15.setText("Bai 15");
        BT15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BT15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT15ActionPerformed(evt);
            }
        });

        exitButton.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 0, 0));
        exitButton.setText("EXIT");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(memberTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(funtionTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(member1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(member2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(member3))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(member4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(member5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BT5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BT2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT10, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT14, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BT15, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(50, 50, 50)
                                    .addComponent(BT3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(BT7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BT11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BT8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT12, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(groupTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(groupTitle)
                .addGap(18, 18, 18)
                .addComponent(memberTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(member1)
                    .addComponent(member4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(member2)
                    .addComponent(member5))
                .addGap(18, 18, 18)
                .addComponent(member3)
                .addGap(26, 26, 26)
                .addComponent(funtionTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void BT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT1ActionPerformed
        Bai1 bt1 = new Bai1();
        bt1.setVisible(true);
    }//GEN-LAST:event_BT1ActionPerformed

    private void BT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT2ActionPerformed
        Bai2 bt2 = new Bai2();
        bt2.setVisible(true);
    }//GEN-LAST:event_BT2ActionPerformed

    private void BT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT3ActionPerformed
        Bai3 bt3 = new Bai3();
        bt3.setVisible(true);
    }//GEN-LAST:event_BT3ActionPerformed

    private void BT4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT4ActionPerformed
        Bai4 bt4 = new Bai4();
        bt4.setVisible(true);
    }//GEN-LAST:event_BT4ActionPerformed

    private void BT5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT5ActionPerformed
        Bai5 bt5 = new Bai5();
        bt5.setVisible(true);
    }//GEN-LAST:event_BT5ActionPerformed

    private void BT6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT6ActionPerformed
        Bai6 bt6 = new Bai6();
        bt6.setVisible(true);
    }//GEN-LAST:event_BT6ActionPerformed

    private void BT7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT7ActionPerformed
        Bai7 bt7 = new Bai7();
        bt7.setVisible(true);
    }//GEN-LAST:event_BT7ActionPerformed

    private void BT8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT8ActionPerformed
        Bai8 bt8 = new Bai8();
        bt8.setVisible(true);
    }//GEN-LAST:event_BT8ActionPerformed

    private void BT9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT9ActionPerformed
        Bai9 bt9 = new Bai9();
        bt9.setVisible(true);
    }//GEN-LAST:event_BT9ActionPerformed

    private void BT10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT10ActionPerformed
        Bai10 bt10 = new Bai10();
        bt10.setVisible(true);
    }//GEN-LAST:event_BT10ActionPerformed

    private void BT11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT11ActionPerformed
        Bai11 bt11 = new Bai11();
        bt11.setVisible(true);
    }//GEN-LAST:event_BT11ActionPerformed

    private void BT12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT12ActionPerformed
        Bai12 bt12 = new Bai12();
        bt12.setVisible(true);

    }//GEN-LAST:event_BT12ActionPerformed

    private void BT13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT13ActionPerformed
        Bai13 bt13 = new Bai13();
        bt13.setVisible(true);
    }//GEN-LAST:event_BT13ActionPerformed

    private void BT14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT14ActionPerformed
        Bai14 bt14 = new Bai14();
        bt14.setVisible(true);
    }//GEN-LAST:event_BT14ActionPerformed

    private void BT15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT15ActionPerformed
        Bai15 bt15 = new Bai15();
        bt15.setVisible(true);
    }//GEN-LAST:event_BT15ActionPerformed

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT1;
    private javax.swing.JButton BT10;
    private javax.swing.JButton BT11;
    private javax.swing.JButton BT12;
    private javax.swing.JButton BT13;
    private javax.swing.JButton BT14;
    private javax.swing.JButton BT15;
    private javax.swing.JButton BT2;
    private javax.swing.JButton BT3;
    private javax.swing.JButton BT4;
    private javax.swing.JButton BT5;
    private javax.swing.JButton BT6;
    private javax.swing.JButton BT7;
    private javax.swing.JButton BT8;
    private javax.swing.JButton BT9;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel funtionTitle;
    private javax.swing.JLabel groupTitle;
    private javax.swing.JLabel mainTitle;
    private javax.swing.JLabel member1;
    private javax.swing.JLabel member2;
    private javax.swing.JLabel member3;
    private javax.swing.JLabel member4;
    private javax.swing.JLabel member5;
    private javax.swing.JLabel memberTitle;
    // End of variables declaration//GEN-END:variables
}
